// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo6AkonwEAttadiyVwscM6EspT8X-eXwc',
    appId: '1:552535235656:web:cb277b0e49d33525f4cc7d',
    messagingSenderId: '552535235656',
    projectId: 'instagram-clone-1d881',
    authDomain: 'instagram-clone-1d881.firebaseapp.com',
    storageBucket: 'instagram-clone-1d881.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjWnDXldZ_EHn-qoToj8SIl_6CB-t9kIA',
    appId: '1:552535235656:android:284f61aef5b5c8acf4cc7d',
    messagingSenderId: '552535235656',
    projectId: 'instagram-clone-1d881',
    storageBucket: 'instagram-clone-1d881.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3IA0jF63PnyjX8UOKZlmrrHJ_CbBcODI',
    appId: '1:552535235656:ios:140968517114e733f4cc7d',
    messagingSenderId: '552535235656',
    projectId: 'instagram-clone-1d881',
    storageBucket: 'instagram-clone-1d881.appspot.com',
    iosBundleId: 'com.example.instagramCloneFlutter',
  );
}
